const domainEvents = {
  ACTION: {
    REMOVE: 'REMOVE',
    NOTACCEPT: 'NOTACCEPT',
    ADD: 'ADD',
    UPDATE: 'UPDATE',
    UPLOADED: 'UPLOADED',
  },
  DES: {
    CONTENT_PAGE: 'CONTENT_PAGE',
    DATA_ROOM_DETAIL_PAGE: 'DATA_ROOM_DETAIL_PAGE',
    SETTINGS_NDA_PAGE: 'SETTINGS_NDA_PAGE',
    UPLOAD_FILE_MODAL: 'UPLOAD_FILE_MODAL',
    MODIFY_PERMISSION_MODAL: 'MODIFY_PERMISSION_MODAL',
  },
  FOLDER_ONCHANGE_DOMAINEVENT: 'FOLDER_ONCHANGE_DOMAINEVENT',
  FILE_ONCHANGE_DOMAINEVENT: 'FILE_ONCHANGE_DOMAINEVENT',
  DATA_ROOM_ONCHANGE_DOMAINEVENT: 'DATA_ROOM_ONCHANGE_DOMAINEVENT',
  LINK_ONCHANGE_DOMAINEVENT: 'LINK_ONCHANGE_DOMAINEVENT',
  CHANGE_ACCOUNT_NAME_DOMAINEVENT: 'CHANGE_ACCOUNT_NAME_DOMAINEVENT',
};

export default domainEvents;
